### PR TITLE
Port to .NET Core

### PR DESCRIPTION
**Pull request by jvandertil**
I've made a best effort to port this library to the .NET standard, which unfortunately removes .NET 4.0 support without a lot of 'ifdef' statements.

Known issue: Not all overloads of ```Activator.CreateInstance``` are available, thus a for loop is used to determine the correct constructor to invoke.

Please let me know if you're interested in merging this in.

### CODE REVIEW

**Comment by davidebbo** [comment]
I'm sadly still fairly inexperienced about .NET Core. When you say it removes .NET 4.0 support, do you mean exactly 4.0 (which is ancient), or any 4.x version (e.g. current is 4.6.2)?

**Comment by jvandertil** [comment]
I meant to say exactly .NET 4.0, I've added support for .NET 4.5 (net45) and .NET standard 1.5. This should keep support for 4.5 and up.

At the moment I'm trying to split some commits and get a cleaner diff to make the changes I made more clear. This hopefully makes it easier to review this pull request.

**Comment by jvandertil** [comment]
Split the restructuring from the porting of the code, diff should be easier to review now.

**Comment by davidebbo** [comment]
I see. So for most current users, they would be able to upgrade with good compat?

To be honest, I haven't done much with this package in quite a while, and I don't have a lot of time to maintain it. So if you want to move forward with this, I think I would ask you to become a maintainer. Are you up for that?

One high level comment glancing at the code: Core tooling is moving away from xproj very soon, and moving back to csproj. VS builds should be available quite soon. Not sure if it makes sense to wait for it, or convert later (xproj will be deprecated).

**Comment by jvandertil** [comment]
Yes, for most users (assuming they are targeting .NET 4.5 or higher) it will just be an update of the NuGet package.

It is unfortunate that there is a lot of churn on the .NET Core tooling (and .NET Standard as well), and that a port to the new csproj structure has to be done in the near future. I was under the impression that the move from xproj+project.json to csproj would be largely automated, so I'm not that concerned at the moment about this.

There are still some things missing in this port I realized, most notable the lack of strong naming on the assembly. So it might be best to create a new branch with the .NET core support and perhaps release the .NET Core compatible NuGet as an alpha/beta release.

As for me becoming the maintainer of this package, I think that won't be a problem. It seems that this package is relatively stable (the last nuget publish is almost 2 years ago).

**Comment by davidebbo** [comment]
Sorry for going silent on this. Busy time!

With your changes, how exactly does one build the assembly? I tried running `nuget restore` at the root and it blew up with

    Unable to resolve 'ReflectionMagic' for '.NETCoreApp,Version=v1.0'

**Comment by jvandertil** [comment]
I use the dotnet cli tooling to build, VS2015 with .NET Core tooling also works. Running 'dotnet restore' and 'dotnet build' in src/ReflectionMagic should build.

I noticed that the MSBuild tooling has been released as alpha/preview so I will attempt to port this pull request to that later today/tomorrow.

I'm writing this from my phone, excuse any formatting or spelling errors.

**Comment by jvandertil** [comment]
Updated the BuildNugetPackages.cmd script to use the dotnet cli tooling to restore packages, run the unit tests, and build the Nuget packages on Release.

**Comment by davidebbo** [comment]
I was able to build, and do a quick test. Seems to run great!

**Comment by davidebbo** [comment]
One thing that got lost is the signing logic, which works like [this](https://github.com/davidebbo/ReflectionMagic/blob/0bc074e798f46875864dbe9def8cb5a1ffc7bc6f/ReflectionMagic/ReflectionMagic.csproj#L65-L69). Basically on my machine I set `PRIVATE_SNK_FILE` and point it to my snk file, and it uses it to sign.

Even though I'm not a fan of signing assemblies, it's a big deal for some people. Maybe it's easier to get this back if you first move up to Preview3 tooling which uses csproj?

**Pull request merged**
