### PR TITLE
Support .NET Standard 2.0

### LINKED ISSUE #15: Support .NET Standard 2.0
Shouldn't be a lot of work to support .NET Standard 2.0

### PR DESCRIPTION
**Pull request by jvandertil**
Implemented support for .NET Standard 2.0. 

Will wait with merging this until .NET Standard 2.0 goes RTM. 

Fixes #15.

### CODE REVIEW

**Comment by djowatts** [comment]
Is there a reason this is sitting in a pull request since its been approved? Would be great to have the .Net Standard 2.0 stuff in

**Comment by davidebbo** [comment]
I'll let @jvandertil merge this in when he's ready.

**Comment by jvandertil** [comment]
Thanks for bringing this to my attention @djowatts, I had forgot about it a bit. There is no other reason than a lack of time. I'll have a look at this tonight and push a new version out.

**Comment by jvandertil** [comment]
@djowatts I just published a pre-release package including .NET Standard 2.0 support. I don't expect any issues, so I'll probably send out the final version somewhere next week. If you run into anything feel free to log an issue.

**Comment by djowatts** [comment]
Awesome. I'll try it out tomorrow and let you know if I run into any issues.

On 1 Nov 2017 22:48, "Jos van der Til" <notifications@github.com> wrote:

@djowatts <https://github.com/djowatts> I just published a pre-release
package including .NET Standard 2.0 support. I don't expect any issues, so
I'll probably send out the final version somewhere next week. If you run
into anything feel free to log an issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/davidebbo/ReflectionMagic/pull/16#issuecomment-341266275>,
or mute the thread

**Pull request merged**
